// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI1I2M5ps7h6Vxm0mEtuCW2y3YdZ9R8h4',
    appId: '1:562471901898:web:055777731de2d4aa87f233',
    messagingSenderId: '562471901898',
    projectId: 'project-zoe-7f87a',
    authDomain: 'project-zoe-7f87a.firebaseapp.com',
    storageBucket: 'project-zoe-7f87a.firebasestorage.app',
    measurementId: 'G-XJK6VG0H4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMlXnsqNpr3DjqQncjjyABqgfq_bt3awA',
    appId: '1:562471901898:android:2910cb9abec86ebc87f233',
    messagingSenderId: '562471901898',
    projectId: 'project-zoe-7f87a',
    storageBucket: 'project-zoe-7f87a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBjH6h1O_ZFBtVa2Cv91hhUlZq7jgTQxE',
    appId: '1:562471901898:ios:f81749f3fedd64e787f233',
    messagingSenderId: '562471901898',
    projectId: 'project-zoe-7f87a',
    storageBucket: 'project-zoe-7f87a.firebasestorage.app',
    iosBundleId: 'org.projectzoe.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBjH6h1O_ZFBtVa2Cv91hhUlZq7jgTQxE',
    appId: '1:562471901898:ios:f81749f3fedd64e787f233',
    messagingSenderId: '562471901898',
    projectId: 'project-zoe-7f87a',
    storageBucket: 'project-zoe-7f87a.firebasestorage.app',
    iosBundleId: 'org.projectzoe.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI1I2M5ps7h6Vxm0mEtuCW2y3YdZ9R8h4',
    appId: '1:562471901898:web:c1b6fe83e6893a3f87f233',
    messagingSenderId: '562471901898',
    projectId: 'project-zoe-7f87a',
    authDomain: 'project-zoe-7f87a.firebaseapp.com',
    storageBucket: 'project-zoe-7f87a.firebasestorage.app',
    measurementId: 'G-1V9M8JCQZL',
  );
}
